// <auto-generated />
using Lab17_Blazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab17_Blazor.Migrations
{
    [DbContext(typeof(TablesContext))]
    [Migration("20230515201817_migrationtoDb1")]
    partial class migrationtoDb1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Lab17_Blazor.Data.Models.Table1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Table1s");

                    b.ToTable("table1s");
                });

            modelBuilder.Entity("Lab17_Blazor.Data.Models.Table2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Table1Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK__Table2s");

                    b.HasIndex("Table1Id");

                    b.ToTable("table2s");
                });

            modelBuilder.Entity("Lab17_Blazor.Data.Models.Table2", b =>
                {
                    b.HasOne("Lab17_Blazor.Data.Models.Table1", "Table1")
                        .WithMany("Table2s")
                        .HasForeignKey("Table1Id")
                        .IsRequired()
                        .HasConstraintName("FK_Table2s_Table1s");

                    b.Navigation("Table1");
                });

            modelBuilder.Entity("Lab17_Blazor.Data.Models.Table1", b =>
                {
                    b.Navigation("Table2s");
                });
#pragma warning restore 612, 618
        }
    }
}
